from django.urls import path
from .views import (
    ProductListCreateView,
    ProductDetailView,
    CategoryListView,
    BrandListView,
    TagListView,
    ProductImageUploadView,
    RelatedProductsView,
    AddReviewView,
    SellerProductsView,
    DeleteProductImageView,
    FeaturedProductsView,
    LatestProductsView,
    BestSellerProductsView,
    FeaturedCategoriesView,
    AdminProductsView,
    ApproveRejectProductView,
    AdminCategoriesView,
    AdminDeleteCategoryView,
    AdminUpdateCategoryView,
    AdminTagsView,
    AdminDeleteTagView,
    WishlistRemoveView,
    WishlistView,
)

urlpatterns = [
    path("products/", ProductListCreateView.as_view()),
    path("products/<int:pk>/", ProductDetailView.as_view()),
    path("categories/", CategoryListView.as_view()),
    path("brands/", BrandListView.as_view()),
    path("tags/", TagListView.as_view()),
    path("products/<int:product_id>/upload-images/", ProductImageUploadView.as_view()),
    path("products/<int:pk>/related/", RelatedProductsView.as_view()),
    path("products/<int:product_id>/reviews/", AddReviewView.as_view()),
    path("seller/products/", SellerProductsView.as_view()),
    path("products/images/<int:image_id>/", DeleteProductImageView.as_view()),
    path("products/featured/", FeaturedProductsView.as_view()),
    path("products/latest/", LatestProductsView.as_view()),
    path("products/best-sellers/", BestSellerProductsView.as_view()),
    path("categories/featured/", FeaturedCategoriesView.as_view()),
    path("admin/products/", AdminProductsView.as_view()),
    path("admin/products/<int:product_id>/status/", ApproveRejectProductView.as_view()),
    path("admin/categories/", AdminCategoriesView.as_view()),
    path("admin/categories/<int:category_id>/", AdminDeleteCategoryView.as_view()),
    path("admin/categories/<int:category_id>/update/", AdminUpdateCategoryView.as_view()),
    path("admin/tags/", AdminTagsView.as_view()),
    path("admin/tags/<int:tag_id>/", AdminDeleteTagView.as_view()),
    path("wishlist/", WishlistView.as_view()),
    path("wishlist/<int:product_id>/", WishlistRemoveView.as_view()),
]
