# Generated by Django 6.0 on 2025-12-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_reset_password_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
